docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
site_name: laminas-mvc-plugin-fileprg
site_description: 'laminas-mvc-plugin-fileprg: Post-Redirect-Get controller plugin specifically for laminas-mvc, specifically for handling file uploads'
repo_url: 'https://github.com/laminas/laminas-mvc-plugin-fileprg'
